# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7203bfa39536941480abb37f8f9b0afd66f2176551ec31ce19fcdd229a3f914c59f361145897db685d6b25140642f1ef05001e5634f206c346eafbb787d4c837

test:
  secret_key_base: 2d481f2c96bdfe8601f92669a7c770cba81beac7bbeecd06ea9f5d70c3aeb7fb1bb2d64bbb2c49218fe478b9dc65c7eaa99fd32f8b68929bc6699beaa7837231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
